### ISSUE TITLE
pre-register -> register

### ISSUE THREAD

**Issue by jbee37142** [fedgkr/feconf2020#46]
### nav bar

![image](https://user-images.githubusercontent.com/17924127/95884582-40aa2200-0db7-11eb-8620-e8f324bf30bb.png)

- 버튼: 사전 등록하기 -> 알림 설정하기
- 클릭 시, youtube channel로 랜딩

### pre-register section

![image](https://user-images.githubusercontent.com/17924127/95884467-1ce6dc00-0db7-11eb-8976-aa0fc9bea67c.png)

pre-register section 의 title은 Thanks for Pre-registration

![image](https://user-images.githubusercontent.com/17924127/95884485-253f1700-0db7-11eb-8f03-9f5dc8192d7f.png)

- 버튼: 사전 등록하기 -> 알림 설정하기
- 클릭 시, youtube channel로 랜딩

**Comment by JaeYeopHan** [comment]
갓주영님이 이미 해결
